#!/usr/bin/env python
"""
Scrape library names and URLs from HTML

Generates "library name<tab>URL" output

Base structure looks like:

<P class=pgTitle>Public Libraries - Hours and Locations</P>
<ul class="subMenu"><strong>Abrams Village</strong><br />
    <li class="A_Item"><strong><a href="index.php3?number=1031746&amp;lang=E">Biblioth&egrave;que publique d'Abram-Village</a></strong><br />
    <br />
    <strong>Alberton</strong></li>
    <li class="A_Item"><strong><a href="index.php3?number=1031782&amp;lang=E">Alberton Public Library</a></strong><br />
    <br />
    <strong>Borden-Carleton</strong></li>
    <li class="A_Item"><strong><a href="index.php3?number=1031795&amp;lang=E">Borden-Carleton Public Library</a></strong><br />
"""

import html5lib
import requests

pei_libs = 'http://www.library.pe.ca/libraries'

r = requests.get(pei_libs)
ns = { 'xhtml': 'http://www.w3.org/1999/xhtml' }
doc = html5lib.parse(r.text)
for li in doc.findall('.//xhtml:ul[@class="subMenu"]/xhtml:li', ns):
    print("%s\t%s/%s" % (
        li.find('.//xhtml:a', ns).text,
        'http://www.library.pe.ca',
        li.find('.//xhtml:a', ns).get('href').rstrip('&lang=E')
    ))
